# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ObjcPodLib' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ObjcPodLib
  source 'https://github.com/xuzhao-nick/podspecs.git'
  pod 'TestPodLib', '~> 1.0.0'
end
